name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        run: npm test  # Adjust this command to match your test setup (e.g., playwright or cypress)

      # Step 5: Archive test results as an artifact (using a different strategy)
      - name: Archive test results
        run: |
          mkdir -p artifacts
          mv path/to/your/test-results.xml artifacts/
          tar -czf artifacts.tar.gz artifacts

      # Step 6: Upload the artifact (custom method)
      - name: Upload test results artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: artifacts.tar.gz