name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, firefox]

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Install wait-on to wait for the server to be ready
      - name: Install wait-on
        run: npm install wait-on

      # Step 5: Start the development server and capture logs
      - name: Start development server
        run: |
          npm run dev > server.log 2>&1 &  # Capture logs of the server output

      # Step 6: Display server logs for debugging
      - name: Display server logs
        run: cat server.log  # Output server logs to GitHub Actions for debugging

      # Step 7: Wait for the server to be ready
      - name: Wait for server to be ready
        run: |
          npx wait-on --timeout 120000 http://localhost:5173  # Wait for up to 120 seconds (increase timeout)

      # Step 8: Check server status using curl
      - name: Check server status
        run: |
          curl -I http://localhost:5173  # Check if the server is responding

      # Step 9: Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install

      # Step 10: Run Playwright Tests
      - name: Run Tests
        run: npx playwright test --project=${{ matrix.browser }}
        continue-on-error: true
