name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Start the development server
      - name: Start development server
        run: npm run dev &  # Starts the server in the background

      # Step 5: Wait for the server to be ready
      - name: Wait for server to be ready
        run: |
          sleep 10  # Adjust this if the server takes longer to start

      # Step 6: Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install

      # Step 7: Run tests
      - name: Run tests
        run: npm test  # This will run `npx playwright test`
